apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-storage
  labels:
    type: local
spec:
  storageClassName: mysqllocalstorage
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
#
# Provide path to your local host path
# This example works with Windows Fast Ring WSL2 and Docker Desktop Edge Release 2/9/2020
#
  hostPath:
    path: "/run/desktop/mnt/host/c/Users/nsteb/data/mysql"
    # path: "/run/desktop/mnt/host/c/Users/userid/data/mysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-persistent-volume-claim
spec:
  storageClassName: mysqllocalstorage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
